import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import logoS3 from '../../public/logoS3.png';
import logo from '../../public/logo.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <p>This React-based single page application (SPA) is hosted in an Amazon S3 bucket.</p>
          <p>An example of static website hosting using AWS S3.</p>

          <Image
            src={logo}
            alt="App logo"
            className={styles.app_mainlogo}
            priority
          />

          <div className={styles.logos}>
            <Image
              className={styles.app_logoR2L}
              src={logoS3}
              alt="Amazon S3 logo"
              priority
            />
          </div>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Read Amazon S3 Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
